instance:
  id: "controller-1"
  classpath:
    - ../testpackage

drivers:
  - class: unix.drivers.FakeGPIODriver
  - class: unix.drivers.MQTTDriver

devices:
  # Virtual System Devices
  central_bus:
    module_name: CommunicationBus
    name: 'Central Bus'
    server_address: 127.0.0.1
    server_port: 1883
    bind_address: 0.0.0.0
    acl:
      mode: restrictive
      allow:
        - '#bedroom_lamp_1.toggle'

  dummy_logger:
    module_name: Logger

  # Physical devices

#  bedroom_switch:
#    module_name: Button
#    name: 'Bedroom switch'
#    gpio: 8
#    handle_double_click: on
#    handle_long_click: on
#    pipe:
#      click: ['#dummy_logger.log', '#bedroom_lamp_1.toggle']
#      double_click: '#bedroom_lamp_2.toggle'
#      long_click: ['#bedroom_lamp_2.off', '#bedroom_lamp_1.off']


  bedroom_lamp_1:
    module_name: PowerKey
    gpio: 7
    pipe:
      state_changed: ['#central_bus.push_state']

  bedroom_lamp_2:
    module_name: PowerKey
    update_interval: 1000
    gpio: 12

  bathroom_temperature2:
    module_name: 1wireThermometer
    device_id: 5sa2d534
    update_interval: 2000
    pipe:
      state_changed: '#central_bus.push_state'

  bathroom_temperature3:
    module_name: 1wireThermometer
    device_id: 21a5de11df
    update_interval: 3000

  bathroom_temperature1:
    module_name: 1wireThermometer
    device_id: 25544123
    update_interval: 1000
    pipe:
      state_changed: '#central_bus.push_state'